# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# Reference: https://github.com/microsoft/winget-create#building-the-client

properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing Microsoft.VisualStudioCode
        allowPrerelease: true
        securityContext: current
      settings:
        id: "Microsoft.VisualStudioCode"
        source: winget
      id: Microsoft.VisualStudioCode
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing Git.Git
        allowPrerelease: true
        securityContext: current
      settings:
        id: "Git.Git"
        source: winget
      id: Git.Git
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing OpenJS.NodeJS.LTS
        allowPrerelease: true
        securityContext: current
      settings:
        id: "OpenJS.NodeJS.LTS"
        source: winget
      id: OpenJS.NodeJS.LTS
  configurationVersion: 0.2.0
