service: pukhanov-ru

image: pukhanov/pukhanov-ru

servers:
  web:
    hosts:
      - <%= ENV['KAMAL_SERVER_IP'] %>
    options:
      "add-host": host.docker.internal:host-gateway
    labels:
      traefik.http.routers.pukhanov-ru.rule: Host(`pukhanov.ru`)
      traefik.http.routers.pukhanov-ru_secure.rule: Host(`pukhanov.ru`)
      traefik.http.routers.pukhanov-ru_secure.entrypoints: websecure
      traefik.http.routers.pukhanov-ru_secure.tls.certresolver: letsencrypt
      traefik.http.routers.pukhanov-ru_secure.middlewares: www-redirect
      traefik.http.middlewares.www-redirect.redirectRegex.regex: https://www.pukhanov.ru/*
      traefik.http.middlewares.www-redirect.redirectRegex.replacement: https://pukhanov.ru/*

registry:
  server: cr.selcloud.ru
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: <%= ENV['KAMAL_SERVER_USER'] %>

healthcheck:
  port: "80"

env:
  secret:
    - KAMAL_SERVER_IP
    - KAMAL_SERVER_USER
    - KAMAL_REGISTRY_USERNAME
    - KAMAL_REGISTRY_PASSWORD
    - GITHUB_PAT
